---
abstract: 'A user-friendly wrapper to a Tie::IxHash object to fill some use case holes.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092110'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-IxHash-ButMoreFun
provides:
  Tie::IxHash::ButMoreFun:
    file: lib/Tie/IxHash/ButMoreFun.pm
    version: 1.0921204
requires:
  Carp: 0
  Moose: 0.65
  MooseX::Types::Moose: 0
  Test::More: 0
  Test::use::ok: 0.02
  Tie::IxHash: 0
  namespace::autoclean: 0
resources:
  repository: http://github.com/kentfredric/tie-ixhash-butmorefun
version: 1.0921204
